name: envs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: install golang ci lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2
      - name: golangci-lint version
        run: golangci-lint version
      - name: golangci-lint
        run: golangci-lint run -c .golangci.yml ./... -v
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: go mod tidy && go mod download
      - name: run tests
        run: go test ./... -v -p 1 -race
